artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/harshmdev/projects/raw/main/top_10000_movies_data.zip
  local_data_file: artifacts/data_ingestion/top_10000_movies_data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ["comp_df.csv","top_10000_movies_data.zip"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/comp_df.csv
  transformed_data_path: artifacts/data_transformation/tf_data.csv

model_building:
  root_dir: artifacts/model_building
  data_path: artifacts/data_transformation/tf_data.csv
  model_path: artifacts/model_building/recommender_model.pkl

