artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/harshmdev/projects/raw/main/top_10000_movies_data.zip
  local_data_file: artifacts/data_ingestion/top_10000_movies_data.zip
  unzip_dir: artifacts/data_ingestion